name: Update API Deployments

on:
  push:
    branches: [main]
    paths:
      - "Server/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Wait for Render Deployment
        uses: Bounceapp/render-action@330fe789041953f3f0847cf83d038be962037ab7
        with:
          render-token: ${{ secrets.RENDER_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          service-id: srv-co06dof109ks73bp2ji0
          retries: 20
          wait: 16000
          sleep: 30000
